using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SouthernTravelIndiaAgent.SProcedure
{
    /// <summary>
    /// // This class contains the names of stored procedures used in the application.
    /// </summary>
    // <remarks>
    // This class is used to store the names of stored procedures as constants.///
    // It helps in avoiding hardcoding of procedure names throughout the codebase, making it easier to maintain and update.
    // </remarks>
 
    public class StoredProcedures
    {

        public const string ValidateAgent_sp = "ValidateAgent_sp";
        public const string agent_session_details = "agent_session_details";
        public const string SaveAgentLogInInfo_sp = "SaveAgentLogInInfo_sp";
        public const string GetAgentdetails_sp = "GetAgentdetails_sp";
        public const string Agent_Profile = "Agent_Profile";
        public const string Agent_changepassword = "Agent_changepassword";
        public const string Agent_UpdateProfile = "Agent_UpdateProfile";
        public const string Agent_ForgotPassword = "Agent_ForgotPassword";
        public const string AgentTransaction_RPT_SP = "AgentTransaction_RPT_SP";
        public const string Agent_Transactiontypes = "Agent_Transactiontypes";
        public const string GetAgentCommission_sp = "GetAgentCommission_sp";
        public const string sp_InsertEmailLog = "sp_InsertEmailLog";
        public const string Agent_Availablebalance = "Agent_Availablebalance";
        public const string ins_Enq_tbl = "ins_Enq_tbl";
        public const string Get_EnqueryCode = "Get_EnqueryCode";
        public const string Fixedtours_Active = "Fixedtours_Active";
        public const string Fixed_OriginBranches = "Fixed_OriginBranches";
        public const string Fixed_DatewiseTours_Vacantseats = "Fixed_DatewiseTours_Vacantseats";
        public const string BranchWiseTour_Sp = "BranchWiseTour_Sp";
        public const string GetSubLedgerHead_SP = "GetSubLedgerHead_SP";
        public const string SaveAgentLogoutInfo_sp = "SaveAgentLogoutInfo_sp";
        public const string GetHotelInfoValid_sp = "GetHotelInfoValid_sp";
        public const string GetActive_Cat_City_sp = "GetActive_Cat_City_sp";
        public const string Car_TransferTypes_CityWise = "Car_TransferTypes_CityWise";
        public const string SpecialTours_Zonewise = "SpecialTours_Zonewise";
        public const string GetSPLticketCode_sp = "GetSPLticketCode_sp";
        public const string GetSPLpnr_sp = "GetSPLpnr_sp";
        public const string Fixed_RecentBookings = "Fixed_RecentBookings";
        public const string Car_FixedTourDetails_sp = "Car_FixedTourDetails_sp";
        public const string Get_SpecialTour_FarePanel_NEW_sp = "Get_SpecialTour_FarePanel_NEW_sp";
        public const string sp_GetTAXValue = "sp_GetTAXValue";
        public const string GetSPLTourMaster_sp = "GetSPLTourMaster_sp";
        public const string GetInstentBooking_sp = "GetInstentBooking_sp";
        public const string GetAgentPayDetail_sp = "GetAgentPayDetail_sp";
        public const string AgentLavelComm_sp = "AgentLavelComm_sp";
        public const string GST_GetCityListByStateIdAndSearchedCityText = "GST_GetCityListByStateIdAndSearchedCityText";
        public const string GST_InsertFinalSPLTourInfoAgent_sp = "GST_InsertFinalSPLTourInfoAgent_sp";
        public const string GetChildPaxCount_sp = "GetChildPaxCount_sp";
        public const string GetDiscount_sp = "GetDiscount_sp";
        public const string GetSpecialTourFare_sp = "GetSpecialTourFare_sp";
        public const string GetInternational_Country_SP = "GetInternational_Country_SP";
        public const string GetServiceTaxIsAcc_sp = "GetServiceTaxIsAcc_sp";
        public const string GetServiceTaxValue_sp = "GetServiceTaxValue_sp";
        public const string GetLTCCharges_sp = "GetLTCCharges_sp";
        public const string GetOrderID_sp = "GetOrderID_sp";
        public const string sp_GetSeatArrangement = "sp_GetSeatArrangement";
        public const string GetPickupDetail_sp = "GetPickupDetail_sp";
        public const string Get_FixedTour_Fare = "Get_FixedTour_Fare";
        public const string jdates_vacantseats = "jdates_vacantseats";
        public const string Fixed_PickupAddr_DeptTime = "Fixed_PickupAddr_DeptTime";
        public const string Fixed_Default_PickupAddress = "Fixed_Default_PickupAddress";
        public const string dispup_sp = "dispup_sp";
        public const string GetMultiplePickupPoint_sp = "GetMultiplePickupPoint_sp";
        public const string SeatArrangement_sp = "SeatArrangement_sp";
        public const string BlockUnBlockSeats_sp = "BlockUnBlockSeats_sp";
        public const string GetPickUpMAsterRowID_sp = "GetPickUpMAsterRowID_sp";
        public const string GetBusAllot_Detail_sp = "GetBusAllot_Detail_sp";
        public const string sp_NoOfSeats = "sp_NoOfSeats";
        public const string ChkBusTypeAgent_sp = "ChkBusTypeAgent_sp";
        public const string ValidateDiscountAgent_sp = "ValidateDiscountAgent_sp";
        public const string Fixed_TourSerial = "Fixed_TourSerial";
        public const string InsertBookingAgent_sp = "InsertBookingAgent_sp";
        public const string UpdateBookingAgent_sp = "UpdateBookingAgent_sp";
        public const string GetCountryName_SP = "GetCountryName_SP";
        public const string sp_GetCar_Local = "sp_GetCar_Local";
        public const string sp_GetCar_fixed = "sp_GetCar_fixed";
        public const string GetFind_City__sp = "GetFind_City__sp";
        public const string CabBookingAgent = "CabBookingAgent";
        public const string sp_Car_LocalTransfer = "sp_Car_LocalTransfer";
        public const string sp_Car_GetFixedTour = "sp_Car_GetFixedTour";
        public const string sp_Car_LocalSubTransfer = "sp_Car_LocalSubTransfer";
        public const string sp_GetState= "sp_GetState";
        public const string insert_Group_GroupBookingRequest = "insert_Group_GroupBookingRequest";
        public const string InsertPaymentHDFCPG_SP = "InsertPaymentHDFCPG_SP";
        public const string insert_tbl_PaymentDetails = "insert_tbl_PaymentDetails";
        public const string GetCABpnr_sp = "GetCABpnr_sp";
        public const string car_perkm_display = "car_perkm_display";
        public const string car_perkm_display_IsAC = "car_perkm_display_IsAC";
        public const string GetCarPerKMFareMaster_sp = "GetCarPerKMFareMaster_sp";
        public const string insert_tbl_CarTailermade_perkm_log = "insert_tbl_CarTailermade_perkm_log";
        public const string Car_SubTransfertypes = "Car_SubTransfertypes";
        public const string GST_GetCustomerDetail_sp= "GST_GetCustomerDetail_sp";
        public const string GetCustomerDetail_sp = "GetCustomerDetail_sp";
        public const string sp_GetAgent_AvailableBalance= "sp_GetAgent_AvailableBalance";
        public const string GetAgentCommission = "GetAgentCommission";
        public const string GST_InsertFinalAccBookingInfo_sp = "GST_InsertFinalAccBookingInfo_sp";
        public const string GetAccDiscount_sp = "GetAccDiscount_sp";
        public const string GetHotelNames_SP = "GetHotelNames_SP";
        public const string sp_GetPaymentMode = "sp_GetPaymentMode";
        public const string sp_HotelRoomTypes = "sp_HotelRoomTypes";
        public const string GetHotelRooms_Fare_SP = "GetHotelRooms_Fare_SP";
        public const string GetCityName_SP = "GetCityName_SP";
        public const string GetRoomTypeOccupancy_SP = "GetRoomTypeOccupancy_SP";
        public const string GST_GetCityListByStateNameAndSearchedCityText = "GST_GetCityListByStateNameAndSearchedCityText";
        public const string agent_viewreport = "agent_viewreport";
        public const string GetAgentFixedTourDupInfo_sp= "GetAgentFixedTourDupInfo_sp";
        public const string GetAgentFixedTourDupTKT_sp = "GetAgentFixedTourDupTKT_sp";
        public const string sp_TicketCodeByOrderDetail = "sp_TicketCodeByOrderDetail";
        public const string sp_GetTickets_Panel = "sp_GetTickets_Panel";
        public const string DupTicketPrintAgent_sp = "DupTicketPrintAgent_sp";
        public const string GetCancelTktHierarchy_sp = "GetCancelTktHierarchy_sp";
        public const string GetTourTicketBanner_sp = "GetTourTicketBanner_sp";
        public const string AgentHTLAccDupTKT = "AgentHTLAccDupTKT";  
        public const string sp_GetRoomFareWithRoomType = "sp_GetRoomFareWithRoomType";   
        public const string GetAccDattTOMail_sp = "GetAccDattTOMail_sp";
        public const string sp_HotelReceipt_Details = "sp_HotelReceipt_Details";
        public const string GetPayModeOrTerm_sp = "GetPayModeOrTerm_sp";
        public const string GetEmailIDAgent_sp = "GetEmailIDAgent_sp";
        public const string EmailSecurity_sp = "EmailSecurity_sp";
        public const string InsertUpdateAgentBalanceClearence_sp = "InsertUpdateAgentBalanceClearence_sp";
        public const string InternationalTourBal_sp = "InternationalTourBal_sp";
        public const string AllTourBalAgent_sp = "AllTourBalAgent_sp";
        public const string AgentFixedTourInfo_sp = "AgentFixedTourInfo_sp";
        public const string br_can_ticketstring = "br_can_ticketstring";   
        public const string AgentFixedTourDetail_sp = "AgentFixedTourDetail_sp";
        public const string AgentCancelTktPrint_sp = "AgentCancelTktPrint_sp";
        public const string SaveBranchToAgentBooking_SP = "SaveBranchToAgentBooking_SP";
        public const string Agent_can_ticketstring = "Agent_can_ticketstring";
        public const string GetFixedTourCancelPerc_sp = "GetFixedTourCancelPerc_sp";
        public const string AgentBranchCode_sp = "AgentBranchCode_sp";
        public const string JourneyDate_sp = "JourneyDate_sp";
        public const string GetSTaxForCanTkt_SP = "GetSTaxForCanTkt_SP";
        public const string GetAgentCommission_New_sp = "GetAgentCommission_New_sp";
        public const string UpdateFixedTourCancelInfo_sp= "UpdateFixedTourCancelInfo_sp";
        public const string GetTourDetail_sp = "GetTourDetail_sp";
        public const string SaveONTranAdv_sp = "SaveONTranAdv_sp";
        public const string GetBusAllotRec_sp = "GetBusAllotRec_sp";
        public const string GetMultiSeattingChartWithSeats_sp = "GetMultiSeattingChartWithSeats_sp";   
        public const string InsertAgentFixTourInfo_sp= "InsertAgentFixTourInfo_sp";
        public const string GetSplTourTicket_sp = "GetSplTourTicket_sp";
        public const string GetSplVehiclemaster_sp = "GetSplVehiclemaster_sp";
        public const string spl_weekend_cancelpercentage = "spl_weekend_cancelpercentage";
        public const string GetPayMode_sp = "GetPayMode_sp"; 
        public const string GetSplTourCancelTicket_sp = "GetSplTourCancelTicket_sp";  
        public const string UpdateSPLTourCancelInfo_sp = "UpdateSPLTourCancelInfo_sp";
        public const string FixTourBalancecReceipt_sp = "FixTourBalancecReceipt_sp";
        public const string SPLTourBalancecReceipt_sp = "SPLTourBalancecReceipt_sp";
        public const string INTTourBalancecReceipt_sp = "INTTourBalancecReceipt_sp";
        public const string ChkInitialDutySlip_sp = "ChkInitialDutySlip_sp";
        public const string sp_AgentCarcancellation = "sp_AgentCarcancellation";
        public const string GetCancelTicket_sp = "GetCancelTicket_sp";
        public const string UpdateCarCancelInfo_sp = "UpdateCarCancelInfo_sp";
        public const string GetHAccCancelPerc_sp= "GetHAccCancelPerc_sp";
        public const string GetHotelCancelPerc_sp= "GetHotelCancelPerc_sp";
        public const string SaveHACCancelInfo_sp = "SaveHACCancelInfo_sp"; 
        public const string GetSTaxForHACTkt_SP = "GetSTaxForHACTkt_SP";
        public const string GetHAccDetail_sp = "GetHAccDetail_sp";
        public const string BranchHACCancelInfo_sp = "BranchHACCancelInfo_sp";
        public const string GetRoomTypeOccupancyNew_SP = "GetRoomTypeOccupancyNew_SP";
        public const string AccCancelReceipt_sp = "AccCancelReceipt_sp";
        public const string Acccancellation_sp = "Acccancellation_sp";
        public const string GetAgentCarTourDupInfo_sp = "GetAgentCarTourDupInfo_sp";
        public const string GetAgentCarTourDupTKT_sp = "GetAgentCarTourDupTKT_sp";  
        public const string GetEmailCarBooking_sp = "GetEmailCarBooking_sp";
        public const string sp_Agent_CarTicket = "sp_Agent_CarTicket";
        public const string GetAgentSPLTourDupInfo_sp = "GetAgentSPLTourDupInfo_sp";
        public const string GetAgentSPLTourDupTKT_sp = "GetAgentSPLTourDupTKT_sp";
        public const string Special_Ticket = "Special_Ticket";
        public const string GetTour_sp = "GetTour_sp";
        public const string DeleteOnlineToursBooking_sp= "DeleteOnlineToursBooking_sp";
        public const string GetPaxCount_sp = "GetPaxCount_sp";
        public const string GetToursBookingInfoAgent_sp = "GetToursBookingInfoAgent_sp"; 
        public const string GetTourBookTotalAmt_sp = "GetTourBookTotalAmt_sp";  
    }
}